<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL',
  'fetched_at' => '2026-05-15T12:42:59+00:00',
  'checksum' => 'sha256:03d1ed81d89e9a01d74c1b9559745673f91e08f258c604dbf47610756c464b36',
  'ranges_by_octet' => 
  array (
    23 => 
    array (
      0 => '23.0.0.0/12',
      1 => '23.192.0.0/11',
    ),
    38 => 
    array (
      0 => '2600:1400::/32',
    ),
    42 => 
    array (
      0 => '2a02:26f0::/32',
    ),
    63 => 
    array (
      0 => '63.208.192.0/20',
    ),
    72 => 
    array (
      0 => '72.246.0.0/15',
    ),
    77 => 
    array (
      0 => '77.67.0.0/16',
    ),
    88 => 
    array (
      0 => '88.221.0.0/16',
    ),
    92 => 
    array (
      0 => '92.122.0.0/15',
    ),
    95 => 
    array (
      0 => '95.100.0.0/15',
    ),
    96 => 
    array (
      0 => '96.6.0.0/15',
      1 => '96.16.0.0/15',
    ),
    104 => 
    array (
      0 => '104.64.0.0/10',
    ),
    173 => 
    array (
      0 => '173.222.0.0/15',
    ),
    184 => 
    array (
      0 => '184.24.0.0/13',
      1 => '184.84.0.0/14',
    ),
  ),
  'ranges_broad' => 
  array (
  ),
  'note' => 'hand-curated from public RIR records; refresh before release',
);
