<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'https://www.cloudflare.com/ips-v4 + /ips-v6',
  'fetched_at' => '2026-05-15T12:42:59+00:00',
  'checksum' => 'sha256:d89bc053e3ef30a0b3f8340068b73f8b1e4c0f1047248d29f22f10dfffffb177',
  'ranges_by_octet' => 
  array (
    36 => 
    array (
      0 => '2400:cb00::/32',
      1 => '2405:b500::/32',
      2 => '2405:8100::/32',
    ),
    38 => 
    array (
      0 => '2606:4700::/32',
    ),
    40 => 
    array (
      0 => '2803:f800::/32',
    ),
    42 => 
    array (
      0 => '2a06:98c0::/29',
    ),
    44 => 
    array (
      0 => '2c0f:f248::/32',
    ),
    103 => 
    array (
      0 => '103.21.244.0/22',
      1 => '103.22.200.0/22',
      2 => '103.31.4.0/22',
    ),
    104 => 
    array (
      0 => '104.16.0.0/13',
      1 => '104.24.0.0/14',
    ),
    108 => 
    array (
      0 => '108.162.192.0/18',
    ),
    131 => 
    array (
      0 => '131.0.72.0/22',
    ),
    141 => 
    array (
      0 => '141.101.64.0/18',
    ),
    162 => 
    array (
      0 => '162.158.0.0/15',
    ),
    172 => 
    array (
      0 => '172.64.0.0/13',
    ),
    173 => 
    array (
      0 => '173.245.48.0/20',
    ),
    188 => 
    array (
      0 => '188.114.96.0/20',
    ),
    190 => 
    array (
      0 => '190.93.240.0/20',
    ),
    197 => 
    array (
      0 => '197.234.240.0/22',
    ),
    198 => 
    array (
      0 => '198.41.128.0/17',
    ),
  ),
  'ranges_broad' => 
  array (
  ),
);
