<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL',
  'fetched_at' => '2026-05-15T12:42:59+00:00',
  'checksum' => 'sha256:84f57a8e0b6c57361ffdaab714d155701b6a716a44d426076e129ef8088cb950',
  'ranges_by_octet' => 
  array (
    42 => 
    array (
      0 => '2a02:e980::/29',
    ),
    45 => 
    array (
      0 => '45.60.0.0/16',
      1 => '45.64.64.0/22',
    ),
    103 => 
    array (
      0 => '103.28.248.0/22',
    ),
    107 => 
    array (
      0 => '107.154.0.0/16',
    ),
    149 => 
    array (
      0 => '149.126.72.0/21',
    ),
    185 => 
    array (
      0 => '185.11.124.0/22',
    ),
    192 => 
    array (
      0 => '192.230.64.0/18',
    ),
    198 => 
    array (
      0 => '198.143.32.0/19',
    ),
    199 => 
    array (
      0 => '199.83.128.0/21',
    ),
  ),
  'ranges_broad' => 
  array (
  ),
  'note' => 'hand-curated from public RIR records; refresh before release',
);
