<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'https://www.quic.cloud/ips/',
  'fetched_at' => '2026-05-15T12:42:59+00:00',
  'checksum' => 'sha256:2d13f923276748accb479426f5a6b3b2a655ff7a8bf2b7ed24ce1288137d1165',
  'ranges_by_octet' => 
  array (
    35 => 
    array (
      0 => '35.160.82.214/32',
      1 => '35.161.112.60/32',
    ),
    44 => 
    array (
      0 => '44.233.19.45/32',
    ),
    52 => 
    array (
      0 => '52.10.48.182/32',
      1 => '52.13.69.213/32',
    ),
  ),
  'ranges_broad' => 
  array (
  ),
  'note' => 'hand-extracted from HTML page; refresh before release',
);
