<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL',
  'fetched_at' => '2026-05-15T12:42:59+00:00',
  'checksum' => 'sha256:045ea8d8e19fea6383005097d4c21e633d7ad6e615cb72f1954bcf5bffd0a9d3',
  'ranges_by_octet' => 
  array (
    42 => 
    array (
      0 => '2a02:fe80::/29',
    ),
    66 => 
    array (
      0 => '66.248.200.0/22',
    ),
    185 => 
    array (
      0 => '185.93.228.0/22',
    ),
    192 => 
    array (
      0 => '192.88.134.0/23',
    ),
  ),
  'ranges_broad' => 
  array (
  ),
  'note' => 'from Sucuri KB; refresh before release',
);
