<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL',
  'fetched_at' => '2026-05-15T12:43:04+00:00',
  'checksum' => 'sha256:851c7599863127debaee766fd7804e4f71da9a80f1eaca1313b2ac17fb5bca3e',
  'signatures' => 
  array (
    0 => 'sqlmap',
    1 => 'nikto',
    2 => 'nmap',
    3 => 'masscan',
    4 => 'zgrab',
    5 => 'Nessus',
    6 => 'OpenVAS',
    7 => 'w3af',
    8 => 'skipfish',
    9 => 'dirbuster',
    10 => 'gobuster',
    11 => 'wpscan',
    12 => 'acunetix',
    13 => 'netsparker',
    14 => 'WebInspect',
    15 => 'AppScan',
    16 => 'havij',
    17 => 'arachni',
    18 => 'wfuzz',
    19 => 'hydra',
    20 => 'medusa',
    21 => 'feroxbuster',
    22 => 'ffuf',
    23 => 'wget/0',
    24 => 'Baiduspider/test',
    25 => 'Scrapy',
    26 => 'Xenu Link Sleuth',
  ),
  'note' => 'offensive security tools; deliberately excludes generic HTTP-library UAs (python-requests, go-http-client, curl) which have overwhelming legitimate use',
);
