<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL (provider docs — yandex.com/support/webmaster, baidu.com/spider help, datadome.co/bots, seznam-napoveda, naver developer docs, mojeek.com/bot.html)',
  'fetched_at' => '2026-05-15T12:43:04+00:00',
  'checksum' => 'sha256:b72c56bc0de4dbaaa4bde9a8be99801b4743d6e85eb93115842b13b6457ab523',
  'note' => 'Each provider entry binds a UA-token list (case-insensitive substring match, same semantics as ua-search-engines.php) to the documented PTR suffixes. Classifier consults this map only after the bundled IpRangeLookup misses, so the rDNS round-trip is paid solely for providers whose IP ranges we deliberately do not bundle.',
  'providers' => 
  array (
    'baidu' => 
    array (
      'tokens' => 
      array (
        0 => 'Baiduspider',
        1 => 'Baiduspider-image',
      ),
      'suffixes' => 
      array (
        0 => '.crawl.baidu.com',
        1 => '.baidu.jp',
      ),
    ),
    'mojeek' => 
    array (
      'tokens' => 
      array (
        0 => 'MojeekBot',
      ),
      'suffixes' => 
      array (
        0 => '.mojeek.com',
      ),
    ),
    'naver' => 
    array (
      'tokens' => 
      array (
        0 => 'NaverBot',
        1 => 'Yeti',
      ),
      'suffixes' => 
      array (
        0 => '.naver.com',
      ),
    ),
    'seznam' => 
    array (
      'tokens' => 
      array (
        0 => 'SeznamBot',
      ),
      'suffixes' => 
      array (
        0 => '.seznam.cz',
      ),
    ),
    'sogou' => 
    array (
      'tokens' => 
      array (
        0 => 'Sogou',
        1 => 'Sogou web spider',
      ),
      'suffixes' => 
      array (
        0 => '.crawl.sogou.com',
        1 => '.sogou.com',
      ),
    ),
    'yandex' => 
    array (
      'tokens' => 
      array (
        0 => 'YandexBot',
        1 => 'YandexImages',
        2 => 'YandexMobileBot',
      ),
      'suffixes' => 
      array (
        0 => '.yandex.com',
        1 => '.yandex.ru',
        2 => '.yandex.net',
      ),
    ),
    'petal' =>
    array (
      'tokens' =>
      array (
        0 => 'PetalBot',
      ),
      'suffixes' =>
      array (
        0 => '.petalsearch.com',
      ),
    ),
  ),
);
