<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL (provider docs)',
  'fetched_at' => '2026-05-15T12:43:04+00:00',
  'checksum' => 'sha256:5cadbaa0aab880605b18b80caef8a360cfd8d75001cf4143a1549ee7d2f5f77a',
  'signatures' => 
  array (
    0 => 'Googlebot',
    1 => 'Googlebot-Image',
    2 => 'Googlebot-News',
    3 => 'Googlebot-Video',
    4 => 'AdsBot-Google',
    5 => 'Mediapartners-Google',
    6 => 'Google-InspectionTool',
    7 => 'Storebot-Google',
    8 => 'Bingbot',
    9 => 'AdIdxBot',
    10 => 'BingPreview',
    11 => 'MicrosoftPreview',
    12 => 'DuckDuckBot',
    13 => 'Applebot',
    14 => 'Applebot-Extended',
    15 => 'YandexBot',
    16 => 'YandexImages',
    17 => 'YandexMobileBot',
    18 => 'Baiduspider',
    19 => 'Baiduspider-image',
    20 => 'Sogou',
    21 => 'Sogou web spider',
    22 => 'SeznamBot',
    23 => 'NaverBot',
    24 => 'Yeti',
    25 => 'MojeekBot',
    26 => 'AhrefsBot',
    27 => 'SemrushBot',
    28 => 'PetalBot',
    29 => 'Barkrowler',
    30 => 'MJ12bot',
    31 => 'DotBot',
  ),
);
