<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL',
  'fetched_at' => '2026-05-15T12:43:03+00:00',
  'checksum' => 'sha256:622b7f6819b0530267e7227f1538393ae40170ada8392c44a9272a13824bfa3d',
  'ranges_by_octet' => 
  array (
    17 => 
    array (
      0 => '17.0.0.0/8',
    ),
    38 => 
    array (
      0 => '2620:149::/32',
    ),
  ),
  'ranges_broad' => 
  array (
  ),
  'note' => 'coarse 17.0.0.0/8; Apple publishes no finer-grained Applebot list',
);
