<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL (https://duckduckgo.com/duckduckbot)',
  'fetched_at' => '2026-05-15T12:43:04+00:00',
  'checksum' => 'sha256:acc10592153316dee31c6b619d5addd1c26acde59344c4415a266f6c1b66fb48',
  'ranges_by_octet' => 
  array (
    50 => 
    array (
      0 => '50.16.241.113/32',
      1 => '50.16.241.114/32',
      2 => '50.16.241.117/32',
      3 => '50.16.247.234/32',
    ),
    52 => 
    array (
      0 => '52.204.97.23/32',
      1 => '52.5.190.19/32',
    ),
    54 => 
    array (
      0 => '54.208.102.37/32',
      1 => '54.197.234.188/32',
      2 => '54.208.100.22/32',
    ),
    107 => 
    array (
      0 => '107.21.1.8/32',
      1 => '107.20.237.51/32',
    ),
  ),
  'ranges_broad' => 
  array (
  ),
  'note' => 'DuckDuckGo publishes IPs on a docs page; refresh before release',
);
