<?php
// Auto-generated by bin/update-bot-data.php. Do not edit by hand.
// Run bin/update-bot-data.php to refresh.

return array (
  'source_url' => 'MANUAL (https://docs.perplexity.ai/guides/bots)',
  'fetched_at' => '2026-05-15T12:43:04+00:00',
  'checksum' => 'sha256:360a4b9c14bff10d4b4171baaca1956a35c4d3e2d6591e39e56895fa79506f79',
  'ranges_by_octet' => 
  array (
    34 => 
    array (
      0 => '34.203.217.1/32',
    ),
    44 => 
    array (
      0 => '44.221.181.83/32',
      1 => '44.228.197.0/24',
    ),
  ),
  'ranges_broad' => 
  array (
  ),
  'note' => 'refresh before release',
);
